/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Parsed receipt markup document.
 *
 * Created by `parse()`. Pass to `resolveResources()` and `render*()` functions
 * to avoid re-parsing the markup.
 */
export declare class Document {

}

/**
 * Parse receipt markup into a Document.
 *
 * The document can be passed to `resolveResources()` and all `render*()`
 * functions. Parsing once and rendering multiple times is more efficient
 * than passing a markup string to each render call.
 */
export declare function parse(source: string): Document

/**
 * Configuration for resource loading and caching.
 *
 * All fields are optional. Provide `resourceDir` for local file paths,
 * `cacheDir` for persistent caching, and `resources` for pre-fetched
 * remote content (from `resolveResources()`).
 */
export interface RenderConfig {
  /** Base directory for resolving relative resource paths (fonts, images). */
  resourceDir?: string
  /** Directory for caching downloaded and processed resources. */
  cacheDir?: string
  /**
   * Pre-fetched remote resource bytes, keyed by URL.
   *
   * Use `resolveResources()` to discover which URLs need fetching,
   * then populate this map before calling render functions.
   */
  resources?: Record<string, Buffer>
}

/**
 * Render a Document to ESC/POS binary commands using the printer's built-in text engine.
 *
 * Returns a Buffer of raw ESC/POS bytes. Images are sent inline as raster data.
 */
export declare function renderEscpos(doc: Document, config?: RenderConfig | undefined | null): Promise<Buffer>

/** Render markup string to ESC/POS binary commands. */
export declare function renderEscposFromMarkup(source: string, config?: RenderConfig | undefined | null): Promise<Buffer>

/**
 * Render a Document to a standalone HTML document.
 *
 * No resources needed — images are `<img>` tags, QR codes and barcodes are inline SVG.
 */
export declare function renderHtml(doc: Document): Promise<string>

/** Render markup string to a standalone HTML document. */
export declare function renderHtmlFromMarkup(source: string): Promise<string>

/**
 * Render a Document to a 1-bit black/white PNG image.
 *
 * Returns a Buffer containing the compressed PNG bytes.
 * Matches thermal printer appearance.
 */
export declare function renderImage(doc: Document, config?: RenderConfig | undefined | null): Promise<Buffer>

/**
 * Render markup string to a 1-bit black/white PNG image.
 *
 * Convenience function that parses and renders in one step.
 * For repeated rendering or remote resources, use `parse()` + `renderImage()`.
 */
export declare function renderImageFromMarkup(source: string, config?: RenderConfig | undefined | null): Promise<Buffer>

/**
 * Render a Document to ESC/POS raster print commands.
 *
 * Returns a Buffer containing the complete ESC/POS byte stream
 * (init + raster image + feed). Send directly to a thermal printer.
 */
export declare function renderRaster(doc: Document, config?: RenderConfig | undefined | null): Promise<Buffer>

/** Render markup string to ESC/POS raster print commands. */
export declare function renderRasterFromMarkup(source: string, config?: RenderConfig | undefined | null): Promise<Buffer>

/**
 * Render a Document to plain text (monospace ASCII).
 *
 * Images, QR codes, and barcodes are rendered as text placeholders.
 */
export declare function renderText(doc: Document): Promise<string>

/** Render markup string to plain text. */
export declare function renderTextFromMarkup(source: string): Promise<string>

/**
 * Discover which remote URLs need to be fetched by the host.
 *
 * Returns an array of HTTPS URLs that are not in the download cache.
 * Fetch these with `fetch()` or your HTTP client, then pass the bytes
 * in `config.resources` when rendering.
 *
 * Returns an empty array if all resources are local or already cached.
 */
export declare function resolveResources(doc: Document, config?: RenderConfig | undefined | null): Array<string>
