/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Configuration for resource loading and caching.
 *
 * Both fields are optional. Even with no paths, HTTPS URLs can still be fetched.
 */
export interface RenderConfig {
  /** Base directory for resolving relative resource paths (fonts, images). */
  resourceDir?: string
  /** Directory for caching downloaded and processed resources. */
  cacheDir?: string
}

/**
 * Render markup to ESC/POS binary commands using the printer's built-in text engine.
 *
 * Returns a Buffer of raw ESC/POS bytes. Images are sent inline as raster data.
 */
export declare function renderEscpos(source: string, config?: RenderConfig | undefined | null): Promise<Buffer>

/**
 * Render markup to a standalone HTML document.
 *
 * No resources needed — images are `<img>` tags, QR codes and barcodes are inline SVG.
 */
export declare function renderHtml(source: string): Promise<string>

/**
 * Render markup to a 1-bit black/white PNG image.
 *
 * Returns a Buffer containing the compressed PNG bytes.
 * Matches thermal printer appearance.
 */
export declare function renderImage(source: string, config?: RenderConfig | undefined | null): Promise<Buffer>

/**
 * Render markup to ESC/POS raster print commands.
 *
 * Returns a Buffer containing the complete ESC/POS byte stream
 * (init + raster image + feed). Send directly to a thermal printer.
 */
export declare function renderRaster(source: string, config?: RenderConfig | undefined | null): Promise<Buffer>

/**
 * Render markup to plain text (monospace ASCII).
 *
 * Images, QR codes, and barcodes are rendered as text placeholders.
 */
export declare function renderText(source: string): Promise<string>
